baseURL: http://example.org/
languageCode: en-us
title: myDocs
theme: mydocs
enableGitInfo: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu: 
  main:
    - name: Git Repos
      pre:  <i class='fab fa-github fa-fw'></i>
      url: https://github.com/twoodby/hugo_docs_theme
      weight: 10



params:
  # Javascript and CSS cache are automatically busted when new version of site is generated.
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting: false
  showSearchBox: true