baseURL = "http://example.org/"
languageCode = "en-us"

title = "Docs Theme Documentation"

#  Theme Settings
theme = "hugo_docs_theme"
themesdir = "../.."

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
    disableBreadcrumb = false
